---
title: "Utilisation de BoutadE avec plusieurs études"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Utilisation de BoutadE avec plusieurs études}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
library(BoutadE)
library(dplyr)
devtools::install_github("clement2323/ollamax")
library(ollamax) #??ollamax
library(pbapply)
library(data.table)
```


```{r}
#Sys.setenv(no_proxy = "")
#Sys.setenv(https_proxy ="http://proxy-rie.http.insee.fr:8080")
#Sys.setenv(http_proxy ="http://proxy-rie.http.insee.fr:8080")

# voir toutes les tables jouets disponibles
data(package = "BoutadE")

data("metadonnees_etude") #  metadonnee d'une etude
str(metadonnees_etude)  # Que pour parler ollama (YODA)


data("metadonnees_tables") #  metadonnee d'une etude
metadonnees_tables %>% head(10) # tu en as besoin

data("EP_FI_AG")
EP_FI_AG %>% head(5)
setDT(EP_FI_AG)

data("table_demandes_valides")
data("table_demandes_erreurs")

```

## Ecriture sur excel
```{r}
metadonnees_tables
```
```{r}
table_demandes <- table_demandes_valides
erreurs <- controler_demandes(table_demandes)
if(nrow(erreurs)!=0) stop("il ya des erreurs dans les demandes")
```

```{r}
# metadonnees_tables <- NULL
# gestion excel ok <-
for (i in 1:nrow(table_demandes)){
    print(i)
    ecrire_demande_sur_xls(table_demandes[i,],metadonnees_tables)
    }
```
```{r}
ecrire_etude

```

```{r}

# gestion excel ok <-
for (i in 1:nrow(table_demandes)){
    print(i)
    ecrire_demande_sur_xls(table_demandes[i,],metadonnees_tables)
    }
```

```{r}

liste_info_chunk <- pblapply(1:nrow(table_demandes_rmd), function(i){ generer_figure_from_demande(table_demandes_rmd[i,], metadonnees_tables)
}
)
```
```{r}
# etude d'un element
element <- liste_info_chunk[[2]]
figure <- element$figure
figure
```

```{r}
nom_rapport <- "rapport_titou.rmd"
# genere le .rmd rapport titou
generer_markdown_auto_simple(liste_info_chunk, nom_rapport = nom_rapport)

```

```{r}

rmarkdown::render(input = paste0("output/", nom_rapport),envir = environment())
```

```{r}

table_demandes_rmd
```
